/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Whitelist } from "./Whitelist";
import { WhitelistCountArgs } from "./WhitelistCountArgs";
import { WhitelistFindManyArgs } from "./WhitelistFindManyArgs";
import { WhitelistFindUniqueArgs } from "./WhitelistFindUniqueArgs";
import { CreateWhitelistArgs } from "./CreateWhitelistArgs";
import { UpdateWhitelistArgs } from "./UpdateWhitelistArgs";
import { DeleteWhitelistArgs } from "./DeleteWhitelistArgs";
import { WhitelistService } from "../whitelist.service";
@graphql.Resolver(() => Whitelist)
export class WhitelistResolverBase {
  constructor(protected readonly service: WhitelistService) {}

  async _whitelistsMeta(
    @graphql.Args() args: WhitelistCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Whitelist])
  async whitelists(
    @graphql.Args() args: WhitelistFindManyArgs
  ): Promise<Whitelist[]> {
    return this.service.whitelists(args);
  }

  @graphql.Query(() => Whitelist, { nullable: true })
  async whitelist(
    @graphql.Args() args: WhitelistFindUniqueArgs
  ): Promise<Whitelist | null> {
    const result = await this.service.whitelist(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Whitelist)
  async createWhitelist(
    @graphql.Args() args: CreateWhitelistArgs
  ): Promise<Whitelist> {
    return await this.service.createWhitelist({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Whitelist)
  async updateWhitelist(
    @graphql.Args() args: UpdateWhitelistArgs
  ): Promise<Whitelist | null> {
    try {
      return await this.service.updateWhitelist({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Whitelist)
  async deleteWhitelist(
    @graphql.Args() args: DeleteWhitelistArgs
  ): Promise<Whitelist | null> {
    try {
      return await this.service.deleteWhitelist(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
