/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Whitelist as PrismaWhitelist } from "@prisma/client";

export class WhitelistServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.WhitelistCountArgs, "select">
  ): Promise<number> {
    return this.prisma.whitelist.count(args);
  }

  async whitelists(
    args: Prisma.WhitelistFindManyArgs
  ): Promise<PrismaWhitelist[]> {
    return this.prisma.whitelist.findMany(args);
  }
  async whitelist(
    args: Prisma.WhitelistFindUniqueArgs
  ): Promise<PrismaWhitelist | null> {
    return this.prisma.whitelist.findUnique(args);
  }
  async createWhitelist(
    args: Prisma.WhitelistCreateArgs
  ): Promise<PrismaWhitelist> {
    return this.prisma.whitelist.create(args);
  }
  async updateWhitelist(
    args: Prisma.WhitelistUpdateArgs
  ): Promise<PrismaWhitelist> {
    return this.prisma.whitelist.update(args);
  }
  async deleteWhitelist(
    args: Prisma.WhitelistDeleteArgs
  ): Promise<PrismaWhitelist> {
    return this.prisma.whitelist.delete(args);
  }
}
