/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { WhitelistService } from "../whitelist.service";
import { WhitelistCreateInput } from "./WhitelistCreateInput";
import { Whitelist } from "./Whitelist";
import { WhitelistFindManyArgs } from "./WhitelistFindManyArgs";
import { WhitelistWhereUniqueInput } from "./WhitelistWhereUniqueInput";
import { WhitelistUpdateInput } from "./WhitelistUpdateInput";

export class WhitelistControllerBase {
  constructor(protected readonly service: WhitelistService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Whitelist })
  async createWhitelist(
    @common.Body() data: WhitelistCreateInput
  ): Promise<Whitelist> {
    return await this.service.createWhitelist({
      data: data,
      select: {
        adminUploadBatch: true,
        createdAt: true,
        email: true,
        id: true,
        location: true,
        name: true,
        participantStatus: true,
        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Whitelist] })
  @ApiNestedQuery(WhitelistFindManyArgs)
  async whitelists(@common.Req() request: Request): Promise<Whitelist[]> {
    const args = plainToClass(WhitelistFindManyArgs, request.query);
    return this.service.whitelists({
      ...args,
      select: {
        adminUploadBatch: true,
        createdAt: true,
        email: true,
        id: true,
        location: true,
        name: true,
        participantStatus: true,
        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Whitelist })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async whitelist(
    @common.Param() params: WhitelistWhereUniqueInput
  ): Promise<Whitelist | null> {
    const result = await this.service.whitelist({
      where: params,
      select: {
        adminUploadBatch: true,
        createdAt: true,
        email: true,
        id: true,
        location: true,
        name: true,
        participantStatus: true,
        phone: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Whitelist })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateWhitelist(
    @common.Param() params: WhitelistWhereUniqueInput,
    @common.Body() data: WhitelistUpdateInput
  ): Promise<Whitelist | null> {
    try {
      return await this.service.updateWhitelist({
        where: params,
        data: data,
        select: {
          adminUploadBatch: true,
          createdAt: true,
          email: true,
          id: true,
          location: true,
          name: true,
          participantStatus: true,
          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Whitelist })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteWhitelist(
    @common.Param() params: WhitelistWhereUniqueInput
  ): Promise<Whitelist | null> {
    try {
      return await this.service.deleteWhitelist({
        where: params,
        select: {
          adminUploadBatch: true,
          createdAt: true,
          email: true,
          id: true,
          location: true,
          name: true,
          participantStatus: true,
          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
